# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nfs/zfs-student-6/users/tmaske/.brew/Cellar/cmake/3.9.1/bin/cmake

# The command to remove a file.
RM = /nfs/zfs-student-6/users/tmaske/.brew/Cellar/cmake/3.9.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /nfs/zfs-student-6/users/tmaske/Bomberman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /nfs/zfs-student-6/users/tmaske/Bomberman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/nfs/zfs-student-6/users/tmaske/.brew/Cellar/cmake/3.9.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/nfs/zfs-student-6/users/tmaske/.brew/Cellar/cmake/3.9.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /nfs/zfs-student-6/users/tmaske/Bomberman/CMakeFiles /nfs/zfs-student-6/users/tmaske/Bomberman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /nfs/zfs-student-6/users/tmaske/Bomberman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Bomberman

# Build rule for target.
Bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bomberman
.PHONY : Bomberman

# fast build rule for target.
Bomberman/fast:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/build
.PHONY : Bomberman/fast

src/Bomb.o: src/Bomb.cpp.o

.PHONY : src/Bomb.o

# target to build an object file
src/Bomb.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Bomb.cpp.o
.PHONY : src/Bomb.cpp.o

src/Bomb.i: src/Bomb.cpp.i

.PHONY : src/Bomb.i

# target to preprocess a source file
src/Bomb.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Bomb.cpp.i
.PHONY : src/Bomb.cpp.i

src/Bomb.s: src/Bomb.cpp.s

.PHONY : src/Bomb.s

# target to generate assembly for a file
src/Bomb.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Bomb.cpp.s
.PHONY : src/Bomb.cpp.s

src/Box.o: src/Box.cpp.o

.PHONY : src/Box.o

# target to build an object file
src/Box.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Box.cpp.o
.PHONY : src/Box.cpp.o

src/Box.i: src/Box.cpp.i

.PHONY : src/Box.i

# target to preprocess a source file
src/Box.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Box.cpp.i
.PHONY : src/Box.cpp.i

src/Box.s: src/Box.cpp.s

.PHONY : src/Box.s

# target to generate assembly for a file
src/Box.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Box.cpp.s
.PHONY : src/Box.cpp.s

src/BreakableBox.o: src/BreakableBox.cpp.o

.PHONY : src/BreakableBox.o

# target to build an object file
src/BreakableBox.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/BreakableBox.cpp.o
.PHONY : src/BreakableBox.cpp.o

src/BreakableBox.i: src/BreakableBox.cpp.i

.PHONY : src/BreakableBox.i

# target to preprocess a source file
src/BreakableBox.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/BreakableBox.cpp.i
.PHONY : src/BreakableBox.cpp.i

src/BreakableBox.s: src/BreakableBox.cpp.s

.PHONY : src/BreakableBox.s

# target to generate assembly for a file
src/BreakableBox.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/BreakableBox.cpp.s
.PHONY : src/BreakableBox.cpp.s

src/Character.o: src/Character.cpp.o

.PHONY : src/Character.o

# target to build an object file
src/Character.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Character.cpp.o
.PHONY : src/Character.cpp.o

src/Character.i: src/Character.cpp.i

.PHONY : src/Character.i

# target to preprocess a source file
src/Character.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Character.cpp.i
.PHONY : src/Character.cpp.i

src/Character.s: src/Character.cpp.s

.PHONY : src/Character.s

# target to generate assembly for a file
src/Character.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Character.cpp.s
.PHONY : src/Character.cpp.s

src/Core.o: src/Core.cpp.o

.PHONY : src/Core.o

# target to build an object file
src/Core.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Core.cpp.o
.PHONY : src/Core.cpp.o

src/Core.i: src/Core.cpp.i

.PHONY : src/Core.i

# target to preprocess a source file
src/Core.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Core.cpp.i
.PHONY : src/Core.cpp.i

src/Core.s: src/Core.cpp.s

.PHONY : src/Core.s

# target to generate assembly for a file
src/Core.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Core.cpp.s
.PHONY : src/Core.cpp.s

src/Drop.o: src/Drop.cpp.o

.PHONY : src/Drop.o

# target to build an object file
src/Drop.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Drop.cpp.o
.PHONY : src/Drop.cpp.o

src/Drop.i: src/Drop.cpp.i

.PHONY : src/Drop.i

# target to preprocess a source file
src/Drop.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Drop.cpp.i
.PHONY : src/Drop.cpp.i

src/Drop.s: src/Drop.cpp.s

.PHONY : src/Drop.s

# target to generate assembly for a file
src/Drop.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Drop.cpp.s
.PHONY : src/Drop.cpp.s

src/EnemyDrop.o: src/EnemyDrop.cpp.o

.PHONY : src/EnemyDrop.o

# target to build an object file
src/EnemyDrop.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/EnemyDrop.cpp.o
.PHONY : src/EnemyDrop.cpp.o

src/EnemyDrop.i: src/EnemyDrop.cpp.i

.PHONY : src/EnemyDrop.i

# target to preprocess a source file
src/EnemyDrop.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/EnemyDrop.cpp.i
.PHONY : src/EnemyDrop.cpp.i

src/EnemyDrop.s: src/EnemyDrop.cpp.s

.PHONY : src/EnemyDrop.s

# target to generate assembly for a file
src/EnemyDrop.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/EnemyDrop.cpp.s
.PHONY : src/EnemyDrop.cpp.s

src/Exceptions.o: src/Exceptions.cpp.o

.PHONY : src/Exceptions.o

# target to build an object file
src/Exceptions.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Exceptions.cpp.o
.PHONY : src/Exceptions.cpp.o

src/Exceptions.i: src/Exceptions.cpp.i

.PHONY : src/Exceptions.i

# target to preprocess a source file
src/Exceptions.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Exceptions.cpp.i
.PHONY : src/Exceptions.cpp.i

src/Exceptions.s: src/Exceptions.cpp.s

.PHONY : src/Exceptions.s

# target to generate assembly for a file
src/Exceptions.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Exceptions.cpp.s
.PHONY : src/Exceptions.cpp.s

src/ExtraBomb.o: src/ExtraBomb.cpp.o

.PHONY : src/ExtraBomb.o

# target to build an object file
src/ExtraBomb.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/ExtraBomb.cpp.o
.PHONY : src/ExtraBomb.cpp.o

src/ExtraBomb.i: src/ExtraBomb.cpp.i

.PHONY : src/ExtraBomb.i

# target to preprocess a source file
src/ExtraBomb.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/ExtraBomb.cpp.i
.PHONY : src/ExtraBomb.cpp.i

src/ExtraBomb.s: src/ExtraBomb.cpp.s

.PHONY : src/ExtraBomb.s

# target to generate assembly for a file
src/ExtraBomb.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/ExtraBomb.cpp.s
.PHONY : src/ExtraBomb.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GraphicsHandler.o: src/GraphicsHandler.cpp.o

.PHONY : src/GraphicsHandler.o

# target to build an object file
src/GraphicsHandler.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/GraphicsHandler.cpp.o
.PHONY : src/GraphicsHandler.cpp.o

src/GraphicsHandler.i: src/GraphicsHandler.cpp.i

.PHONY : src/GraphicsHandler.i

# target to preprocess a source file
src/GraphicsHandler.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/GraphicsHandler.cpp.i
.PHONY : src/GraphicsHandler.cpp.i

src/GraphicsHandler.s: src/GraphicsHandler.cpp.s

.PHONY : src/GraphicsHandler.s

# target to generate assembly for a file
src/GraphicsHandler.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/GraphicsHandler.cpp.s
.PHONY : src/GraphicsHandler.cpp.s

src/LevelHatch.o: src/LevelHatch.cpp.o

.PHONY : src/LevelHatch.o

# target to build an object file
src/LevelHatch.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/LevelHatch.cpp.o
.PHONY : src/LevelHatch.cpp.o

src/LevelHatch.i: src/LevelHatch.cpp.i

.PHONY : src/LevelHatch.i

# target to preprocess a source file
src/LevelHatch.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/LevelHatch.cpp.i
.PHONY : src/LevelHatch.cpp.i

src/LevelHatch.s: src/LevelHatch.cpp.s

.PHONY : src/LevelHatch.s

# target to generate assembly for a file
src/LevelHatch.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/LevelHatch.cpp.s
.PHONY : src/LevelHatch.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/RangeExtender.o: src/RangeExtender.cpp.o

.PHONY : src/RangeExtender.o

# target to build an object file
src/RangeExtender.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/RangeExtender.cpp.o
.PHONY : src/RangeExtender.cpp.o

src/RangeExtender.i: src/RangeExtender.cpp.i

.PHONY : src/RangeExtender.i

# target to preprocess a source file
src/RangeExtender.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/RangeExtender.cpp.i
.PHONY : src/RangeExtender.cpp.i

src/RangeExtender.s: src/RangeExtender.cpp.s

.PHONY : src/RangeExtender.s

# target to generate assembly for a file
src/RangeExtender.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/RangeExtender.cpp.s
.PHONY : src/RangeExtender.cpp.s

src/RemoteDetonator.o: src/RemoteDetonator.cpp.o

.PHONY : src/RemoteDetonator.o

# target to build an object file
src/RemoteDetonator.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/RemoteDetonator.cpp.o
.PHONY : src/RemoteDetonator.cpp.o

src/RemoteDetonator.i: src/RemoteDetonator.cpp.i

.PHONY : src/RemoteDetonator.i

# target to preprocess a source file
src/RemoteDetonator.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/RemoteDetonator.cpp.i
.PHONY : src/RemoteDetonator.cpp.i

src/RemoteDetonator.s: src/RemoteDetonator.cpp.s

.PHONY : src/RemoteDetonator.s

# target to generate assembly for a file
src/RemoteDetonator.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/RemoteDetonator.cpp.s
.PHONY : src/RemoteDetonator.cpp.s

src/Settings.o: src/Settings.cpp.o

.PHONY : src/Settings.o

# target to build an object file
src/Settings.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Settings.cpp.o
.PHONY : src/Settings.cpp.o

src/Settings.i: src/Settings.cpp.i

.PHONY : src/Settings.i

# target to preprocess a source file
src/Settings.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Settings.cpp.i
.PHONY : src/Settings.cpp.i

src/Settings.s: src/Settings.cpp.s

.PHONY : src/Settings.s

# target to generate assembly for a file
src/Settings.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Settings.cpp.s
.PHONY : src/Settings.cpp.s

src/UnbreakableBox.o: src/UnbreakableBox.cpp.o

.PHONY : src/UnbreakableBox.o

# target to build an object file
src/UnbreakableBox.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/UnbreakableBox.cpp.o
.PHONY : src/UnbreakableBox.cpp.o

src/UnbreakableBox.i: src/UnbreakableBox.cpp.i

.PHONY : src/UnbreakableBox.i

# target to preprocess a source file
src/UnbreakableBox.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/UnbreakableBox.cpp.i
.PHONY : src/UnbreakableBox.cpp.i

src/UnbreakableBox.s: src/UnbreakableBox.cpp.s

.PHONY : src/UnbreakableBox.s

# target to generate assembly for a file
src/UnbreakableBox.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/UnbreakableBox.cpp.s
.PHONY : src/UnbreakableBox.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Bomberman"
	@echo "... src/Bomb.o"
	@echo "... src/Bomb.i"
	@echo "... src/Bomb.s"
	@echo "... src/Box.o"
	@echo "... src/Box.i"
	@echo "... src/Box.s"
	@echo "... src/BreakableBox.o"
	@echo "... src/BreakableBox.i"
	@echo "... src/BreakableBox.s"
	@echo "... src/Character.o"
	@echo "... src/Character.i"
	@echo "... src/Character.s"
	@echo "... src/Core.o"
	@echo "... src/Core.i"
	@echo "... src/Core.s"
	@echo "... src/Drop.o"
	@echo "... src/Drop.i"
	@echo "... src/Drop.s"
	@echo "... src/EnemyDrop.o"
	@echo "... src/EnemyDrop.i"
	@echo "... src/EnemyDrop.s"
	@echo "... src/Exceptions.o"
	@echo "... src/Exceptions.i"
	@echo "... src/Exceptions.s"
	@echo "... src/ExtraBomb.o"
	@echo "... src/ExtraBomb.i"
	@echo "... src/ExtraBomb.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GraphicsHandler.o"
	@echo "... src/GraphicsHandler.i"
	@echo "... src/GraphicsHandler.s"
	@echo "... src/LevelHatch.o"
	@echo "... src/LevelHatch.i"
	@echo "... src/LevelHatch.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/RangeExtender.o"
	@echo "... src/RangeExtender.i"
	@echo "... src/RangeExtender.s"
	@echo "... src/RemoteDetonator.o"
	@echo "... src/RemoteDetonator.i"
	@echo "... src/RemoteDetonator.s"
	@echo "... src/Settings.o"
	@echo "... src/Settings.i"
	@echo "... src/Settings.s"
	@echo "... src/UnbreakableBox.o"
	@echo "... src/UnbreakableBox.i"
	@echo "... src/UnbreakableBox.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

